### ISSUE TITLE
Blurry background image on results page

### ISSUE THREAD

**Issue by shashvatshukla** [shashvatshukla/visualising-political-shills#5]
![blur](https://user-images.githubusercontent.com/7630715/54478529-052a2900-480b-11e9-8e63-7023c692b508.png)

I'm using Ubuntu and Firefox.

**Comment by Daniel-OConnor** [comment]
This was intentional, I wanted a different image just to demonstrate that it was a second page that was being loaded. The blurry image is stored in static/twitter2.jpg, this can be replaced with a nicer picture.
