### ISSUE TITLE
Word 'close' shown instead of close icon on Ubuntu/Firefox

### ISSUE THREAD

**Issue by shashvatshukla** [shashvatshukla/visualising-political-shills#6]
![Screenshot from 2019-03-16 16-41-31](https://user-images.githubusercontent.com/7630715/54478557-5fc38500-480b-11e9-9d6a-e67d5ddaf76e.png)

Works fine on Ubuntu/Chrome

This might be more an issue with my own system.

**Comment by Daniel-OConnor** [comment]
https://material.io/tools/icons/?style=baseline
Do the icons on this page display correctly for you? Material icons is the font that is being used to display 'close' as a close icon.

**Comment by samlu1999** [comment]
Try following the steps here https://github.com/google/material-design-icons/issues/713

Go to about:support
Press refresh Firefox

**Comment by shashvatshukla** [comment]
Yup did that, works now. 
Although I've lost all my extensions and configurations. But that's alright.
